package view;

import javax.swing.JOptionPane;
import model.entidades.Medicamento;

public class MedicamentoGUI extends javax.swing.JDialog {

    /**
     * Creates new form MedicamentoGUI
     */
    public MedicamentoGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManagerMedicamento = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ProjetoClinicaMedicaPU").createEntityManager();
        queryMedicamento = java.beans.Beans.isDesignTime() ? null : entityManagerMedicamento.createQuery("from Medicamento m order by m.nome");
        listMedicamento = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryMedicamento.getResultList());
        jPanelBotoes = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jPanelDados = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelSubstancia = new javax.swing.JLabel();
        jLabelPosologia = new javax.swing.JLabel();
        jLabelLaboratorio = new javax.swing.JLabel();
        jLabelGenerico = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldSubstancia = new javax.swing.JTextField();
        jTextFieldPosologia = new javax.swing.JTextField();
        jTextFieldLaboratorio = new javax.swing.JTextField();
        jTextFieldGenerico = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jPanelTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDadosMedicamentos = new javax.swing.JTable();
        jLabelPesquisa = new javax.swing.JLabel();
        jComboBoxPesquisar = new javax.swing.JComboBox();
        jTextFieldPesquisar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");

        jPanelBotoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelBotoes.setLayout(new java.awt.GridLayout(1, 0));

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jButtonNovo);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jButtonSalvar);

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jButtonAlterar);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jButtonExcluir);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelBotoes.add(jButtonCancelar);

        getContentPane().add(jPanelBotoes, java.awt.BorderLayout.NORTH);

        jPanelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabelNome.setText("Nome:");

        jLabelSubstancia.setText("Substancia:");

        jLabelPosologia.setText("Posologia:");

        jLabelLaboratorio.setText("Laboratório:");

        jLabelGenerico.setText("Genérico:");

        jTextFieldNome.setEnabled(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableDadosMedicamentos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nome}"), jTextFieldNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldSubstancia.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableDadosMedicamentos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.substancia}"), jTextFieldSubstancia, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldPosologia.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableDadosMedicamentos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.posologia}"), jTextFieldPosologia, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldLaboratorio.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableDadosMedicamentos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.laboratorio}"), jTextFieldLaboratorio, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldGenerico.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableDadosMedicamentos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.generico}"), jTextFieldGenerico, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabelCodigo.setText("Código:");

        jTextFieldCodigo.setEnabled(false);

        javax.swing.GroupLayout jPanelDadosLayout = new javax.swing.GroupLayout(jPanelDados);
        jPanelDados.setLayout(jPanelDadosLayout);
        jPanelDadosLayout.setHorizontalGroup(
            jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGenerico, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLaboratorio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPosologia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSubstancia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelCodigo)
                        .addComponent(jLabelNome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosLayout.createSequentialGroup()
                        .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldGenerico, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(jTextFieldLaboratorio)
                            .addComponent(jTextFieldPosologia)
                            .addComponent(jTextFieldSubstancia)
                            .addComponent(jTextFieldNome))
                        .addGap(142, 142, 142))
                    .addGroup(jPanelDadosLayout.createSequentialGroup()
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelDadosLayout.setVerticalGroup(
            jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosLayout.createSequentialGroup()
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSubstancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSubstancia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosologia)
                    .addComponent(jTextFieldPosologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLaboratorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGenerico)
                    .addComponent(jTextFieldGenerico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelDados, java.awt.BorderLayout.CENTER);

        jPanelTabela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableDadosMedicamentos.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listMedicamento, jTableDadosMedicamentos);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigo}"));
        columnBinding.setColumnName("Código");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${substancia}"));
        columnBinding.setColumnName("Substancia");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${posologia}"));
        columnBinding.setColumnName("Posologia");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${laboratorio}"));
        columnBinding.setColumnName("Laboratório");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${generico}"));
        columnBinding.setColumnName("Genérico");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTableDadosMedicamentos);
        if (jTableDadosMedicamentos.getColumnModel().getColumnCount() > 0) {
            jTableDadosMedicamentos.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabelPesquisa.setText("Pesquisa:");

        jComboBoxPesquisar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome", "Laboratorio", "Generico" }));
        jComboBoxPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPesquisarActionPerformed(evt);
            }
        });

        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelTabelaLayout = new javax.swing.GroupLayout(jPanelTabela);
        jPanelTabela.setLayout(jPanelTabelaLayout);
        jPanelTabelaLayout.setHorizontalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addGroup(jPanelTabelaLayout.createSequentialGroup()
                        .addComponent(jLabelPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTabelaLayout.setVerticalGroup(
            jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabelaLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPesquisa)
                    .addComponent(jComboBoxPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanelTabela, java.awt.BorderLayout.SOUTH);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        statusComponentes(true);
        listMedicamento.add(new Medicamento());
        int linha = listMedicamento.size() - 1;
        jTableDadosMedicamentos.setRowSelectionInterval(linha, linha);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        int linhaSelecionada = jTableDadosMedicamentos.getSelectedRow();
        Medicamento medi = listMedicamento.get(linhaSelecionada);

        try {
            entityManagerMedicamento.getTransaction().begin();
            entityManagerMedicamento.persist(medi);
            entityManagerMedicamento.getTransaction().commit();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e);
            if (!entityManagerMedicamento.getTransaction().isActive()) {
                entityManagerMedicamento.getTransaction().begin();
            }
            entityManagerMedicamento.getTransaction().rollback();
        }

        atualizaTabela();
        statusComponentes(false);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        if (jTableDadosMedicamentos.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        } else {
            statusComponentes(true);
        }
        atualizaTabela();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        if (jTableDadosMedicamentos.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir");
        } else {
            try {
                int linhaClicada = jTableDadosMedicamentos.getSelectedRow();
                Medicamento pes = listMedicamento.get(linhaClicada);
                entityManagerMedicamento.getTransaction().begin();
                entityManagerMedicamento.remove(pes);
                entityManagerMedicamento.getTransaction().commit();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro: " + e);
                if (!entityManagerMedicamento.getTransaction().isActive()) {
                    entityManagerMedicamento.getTransaction().begin();
                }
                entityManagerMedicamento.getTransaction().rollback();
            }
        }
        atualizaTabela();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        statusComponentes(false);
        atualizaTabela();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBoxPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPesquisarActionPerformed
        atualizaTabela();
    }//GEN-LAST:event_jComboBoxPesquisarActionPerformed

    private void jTextFieldPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyReleased
        atualizaTabela();
    }//GEN-LAST:event_jTextFieldPesquisarKeyReleased

    private void atualizaTabela() {
        String ejbql = "from Medicamento m ";
        String atributo = "";
        if (jComboBoxPesquisar.getSelectedItem().toString().equals("Nome")) {
            atributo = "m.nome";
        }
        if (jComboBoxPesquisar.getSelectedItem().toString().equals("Laboratorio")) {
            atributo = "m.laboratorio";
        }
        if (jComboBoxPesquisar.getSelectedItem().toString().equals("Generico")) {
            atributo = "m.generico";
        }
        String filtro = jTextFieldPesquisar.getText();
        if (filtro.length() > 0 && filtro != null) {
            ejbql += "where upper(" + atributo + ") like '"
                    + filtro.toUpperCase() + "%' ";
        }
        ejbql += "order by " + atributo;

        queryMedicamento = entityManagerMedicamento.createQuery(ejbql);
        listMedicamento.clear();
        listMedicamento.addAll(queryMedicamento.getResultList());
        int linha = listMedicamento.size() - 1;
        if (listMedicamento.size() > 0) {
            jTableDadosMedicamentos.setRowSelectionInterval(linha, linha);
        }
    }

    private void statusComponentes(boolean status) {
        // true: habilita para inserção
        // false: desabilita inserção
        jButtonNovo.setEnabled(!status);
        jButtonAlterar.setEnabled(!status);
        jButtonExcluir.setEnabled(!status);
        jButtonSalvar.setEnabled(status);
        jButtonCancelar.setEnabled(status);

        // Habilitando/desabilitando campos para inserção de dados
        jTextFieldNome.setEnabled(status);
        jTextFieldGenerico.setEnabled(status);
        jTextFieldLaboratorio.setEnabled(status);
        jTextFieldNome.setEnabled(status);
        jTextFieldPesquisar.setEnabled(status);
        jTextFieldPosologia.setEnabled(status);
        jTextFieldSubstancia.setEnabled(status);

        /*
         //Campos de Pesquisa
         jComboBoxPesquisar.setEnabled(!status);
         jTextFieldPesquisar.setEnabled(!status);
         jButtonPesquisar.setEnabled(!status);
         */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManagerMedicamento;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxPesquisar;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelGenerico;
    private javax.swing.JLabel jLabelLaboratorio;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPesquisa;
    private javax.swing.JLabel jLabelPosologia;
    private javax.swing.JLabel jLabelSubstancia;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelDados;
    private javax.swing.JPanel jPanelTabela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDadosMedicamentos;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldGenerico;
    private javax.swing.JTextField jTextFieldLaboratorio;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldPosologia;
    private javax.swing.JTextField jTextFieldSubstancia;
    private java.util.List<Medicamento> listMedicamento;
    private javax.persistence.Query queryMedicamento;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
