package view;

public class Sobre extends javax.swing.JDialog {

    /**
     * Creates new form Sobre
     */
    public Sobre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIFSP = new javax.swing.JPanel();
        jLabelIFSP = new javax.swing.JLabel();
        jPanelDesenvolvedores = new javax.swing.JPanel();
        jLabelDesenvolvedores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelIFSP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelIFSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LogotipoIFSP.jpg"))); // NOI18N
        jLabelIFSP.setText("jLabel1");

        jPanelDesenvolvedores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelDesenvolvedores.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabelDesenvolvedores.setText("Projeto Interdisciplinar Desenvolvido pelos Alunos: Angélica Larissa e Rafael Henrique");

        javax.swing.GroupLayout jPanelDesenvolvedoresLayout = new javax.swing.GroupLayout(jPanelDesenvolvedores);
        jPanelDesenvolvedores.setLayout(jPanelDesenvolvedoresLayout);
        jPanelDesenvolvedoresLayout.setHorizontalGroup(
            jPanelDesenvolvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDesenvolvedoresLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelDesenvolvedores, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDesenvolvedoresLayout.setVerticalGroup(
            jPanelDesenvolvedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDesenvolvedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDesenvolvedores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelIFSPLayout = new javax.swing.GroupLayout(jPanelIFSP);
        jPanelIFSP.setLayout(jPanelIFSPLayout);
        jPanelIFSPLayout.setHorizontalGroup(
            jPanelIFSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDesenvolvedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIFSPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelIFSP, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        jPanelIFSPLayout.setVerticalGroup(
            jPanelIFSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIFSPLayout.createSequentialGroup()
                .addComponent(jLabelIFSP, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDesenvolvedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIFSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelIFSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDesenvolvedores;
    private javax.swing.JLabel jLabelIFSP;
    private javax.swing.JPanel jPanelDesenvolvedores;
    private javax.swing.JPanel jPanelIFSP;
    // End of variables declaration//GEN-END:variables
}
